import Link from "next/link";

import { getSeoArticles } from "@/lib/seoAutomationApi";

export const metadata = {
  title: "SEO Articles",
  description: "Browse published SEO articles generated by the automation system.",
};

export default async function PublicSeoArticlesPage() {
  const articles = await getSeoArticles().catch(() => []);

  return (
    <main className="blog-shell landing">
      <div className="section-content blog-stack">
        <div>
          <p className="section-heading">Automation-published articles</p>
          <p className="section-subtitle">
            Public article listing powered by the FastAPI publisher and PostgreSQL content store.
          </p>
        </div>

        <div className="blog-card-grid">
          {articles
            .filter((article) => article.status === "published")
            .map((article) => (
              <Link key={article.id} href={`/articles/${article.slug}`} className="blog-card">
                <span className="eyebrow-link">Published</span>
                <h2>{article.title}</h2>
                <p>{article.meta_description}</p>
                <div className="blog-card-footer">
                  <span>{article.published_at ? new Date(article.published_at).toLocaleDateString("en-US") : ""}</span>
                  <span className="blog-card-cta">Read article</span>
                </div>
              </Link>
            ))}
        </div>
      </div>
    </main>
  );
}
